### ISSUE TITLE
Investigating bundling issue

### ISSUE THREAD

**Issue by valadas** [DNNCommunity/dnn-elements#1094]
In v0.15.x there was no p-xxxxx.js (partial bundle file) larger than a few Kb.
In v.0.16.x we still have a lot of small files (normal) but one of them grew to almost 5Mb
In current develop branch we only have 12 files including the sourcemaps and the largest grew to 18.4 Mb

We need to investigate what caused things to get bundled together, other than a few exceptions, we should have almost as many files as components and this is no longer the case.

We should probably also investigate that 4-5Mb file but my guess is that maybe it has something large like monaco or jodit, but we need to check.

**Comment by valadas** [comment]
At 55daa48f the 4-5Mb file is there but we still have mostly a large amount of small files.

**Comment by valadas** [comment]
It appears to have started between v0.16.0 and v0.17.0 running a git bisect to try and pinpoint the commit now

**Comment by valadas** [comment]
I have identified the first commit to have caused this issue to be this one, I'll try to investigate more tomorrow:

6bc124edb041242d952e08e8994833c57c184bd9

**Comment by david-poindexter** [comment]
<img src="https://media4.giphy.com/media/L3Kf5sHWvTBjXz5dUL/giphy.gif"/>
