### ISSUE TITLE
dnn-input prefix/suffix may get covered by field label

### ISSUE THREAD

**Issue by valadas** [DNNCommunity/dnn-elements#1199]
We should probably make the prefix/suffix slot transparent before the label slides up on the field or the label may cover the prefix/suffix as in this example:

![image](https://github.com/user-attachments/assets/ed578140-ce98-4e85-adba-f829832baff1)

**Comment by david-poindexter** [comment]
Makes perfect sense.

**Comment by valadas** [comment]
Actually that is already handled, this is not a prefix but the value 0 which is documented on another issue.
