### ISSUE TITLE
Create a monaco editor component

### ISSUE THREAD

**Issue by valadas** [DNNCommunity/dnn-elements#494]
It would be nice if we had a monaco editor web-component wrapper that is easy to use anywhere.

One of the useful places would be to handle https://github.com/DNNCommunity/Dnn.StructuredContent/issues/10

**Comment by david-poindexter** [comment]
I have already begun work on this.  It will be exciting to see this as a possibility for so many use cases!

**Comment by david-poindexter** [comment]
An initial implementation has now been submitted to the `dnn-elements` project via https://github.com/DNNCommunity/dnn-elements/pull/551

**Comment by david-poindexter** [comment]
@valadas it looks like we still have the `dnn-monaco-editor` branch sitting there and no PR has been made yet.  As a reminder, you wanted to put that on a separate branch for review instead of the normal PR process.

**Comment by valadas** [comment]
Yeah, I was kinda too busy to do a good review and wanted to test consumption by a consuming project to make sure it's all ok. If you want we could maybe refresh that this weekend...

**Comment by david-poindexter** [comment]
@valadas I really want to get this branched merged so I can use this in a project.  When can you review?  This has been blocked for almost seven months now.  :(

**Comment by valadas** [comment]
Done, will publish a beta now to test consumption before the official release
