### ISSUE TITLE
Rename Vertical Split view "Left/Right" to "Start/End"

### ISSUE THREAD

**Issue by X3Technology** [DNNCommunity/dnn-elements#552]
Left/Right assuming left-to-right reading.  What about RTL?  Suggest renaming these as "start" and "end".

**Comment by valadas** [comment]
Well, it is literally left and right panels, this does not affect the text direction and we would not want to swap the panels just because of the text-direction. right to left text can still go it.

**Comment by david-poindexter** [comment]
Agreed.
