### ISSUE TITLE
dnn-button issue with reversed and type combinations.

### ISSUE THREAD

**Issue by Raaphe** [DNNCommunity/dnn-elements#776]
When a dnn-button is reversed, certain style types do not function correctly. 

I found that reversed when matched with primary or danger type work accordingly, but not with the other types; secondary and tertiary. The buttons become filled with this dark gray color.

**Comment by valadas** [comment]
May be related with #749 or should at least be tested together...

**Comment by valadas** [comment]
Appears to be fixed now
![image](https://github.com/DNNCommunity/dnn-elements/assets/6371568/7c7ee9c4-5d53-4819-a804-7a1921c667ec)
