### ISSUE TITLE
Add a Progress Indicator

### ISSUE THREAD

**Issue by WillStrohl** [DNNCommunity/dnn-elements#784]
We were going to try to review this to see if we could use it for a new project, but we can't due to missing a key element, which is a progress indicator.  For example, imagine if you're building something to allow a process or upload that takes a longer period of time than a normal page load.  This element would have a visual indication that helps end users to know how far along the process is and when it might end.  I guess the DNN installer does this too. :)

**Comment by david-poindexter** [comment]
I'll be happy to contribute one! It has actually been on my list for a long time and is one that I already have developed. I just need to review it for this project specifically.
