### ISSUE TITLE
npm.js page lost its readme

### ISSUE THREAD

**Issue by valadas** [DNNCommunity/dnn-elements#903]
When we made this into a monorepo and moved the original files into subfolders, the repository lost the root readme file and this is what shows on npm.js

We need to move and/or copy that file to the root or find a way so npm.js points to it.

![image](https://github.com/DNNCommunity/dnn-elements/assets/6371568/757d6026-2716-4559-9e01-4ffcb37ee9ed)

**Comment by david-poindexter** [comment]
Oopsies - yep!
