### ISSUE TITLE
Dropzone allowed extensions is case sensitive

### ISSUE THREAD

**Issue by valadas** [DNNCommunity/dnn-elements#925]
Trying to upload an image ending in `.JPEG` (uppercase) fails.

**Comment by david-poindexter** [comment]
I think #926 addressed a `.jped` vs `.jpeg` issue.  Is the UPPERCASE something different?

**Comment by valadas** [comment]
Is that was just a typo in a comment, the issue is .jpg vs .JPG handling

Been done in #952
